apiVersion: apps/v1
kind: Deployment
metadata:
  name: recovered-test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: recovered-test
  template:
    metadata:
      labels:
        app: recovered-test
    spec:
      containers:
        - name: recovered-test
          image: maupuert/recovered:latest
          ports:
            - containerPort: 9010
#          env:
#            - name: SPRING_PROFILES_ACTIVE
#              value: "prod"
          resources:
            requests:
              memory: "250Mi"
              cpu: "250m"
            limits:
              memory: "500Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 9010
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 9010
            initialDelaySeconds: 30
            periodSeconds: 10
