name: Pipeline SCA,SAST,DAST for DevSecOps
run-name: ${{ github.actor }}  running this pipeline CI
on:
  push:
    branches:
      - main

jobs:
    sast:
        runs-on: ubuntu-latest
        name: Scan SAST, UnitTest and CodeQuality 
        steps:
            - uses: actions/checkout@v3
            - name: Setup jdk
              uses: actions/setup-java@v3
              with:
                java-version: '11'
                distribution: 'temurin'
            - name: Cache Gradle packages
              uses: actions/cache@v1
              with:
                path: ~/.gradle/caches
                key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
                restore-keys: ${{ runner.os }}-gradle
            - name: Cache SonarCloud packages
              uses: actions/cache@v1
              with:
                path: ~/.sonar/cache
                key: ${{ runner.os }}-sonar
                restore-keys: ${{ runner.os }}-sonar
            - name: Build and analyze
              run: ./gradlew build jacocoTestReport sonarqube --info
              env:
                # Needed to get some information about the pull request, if any
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                # SonarCloud access token should be generated from https://sonarcloud.io/account/security/
                SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    sca:
      name: Scan SCA with SNYK
      needs: sast
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@master
        - name: Run SNYK for check vulnerabilities
          uses: snyk/actions/gradle-jdk11@master
          continue-on-error: true
          env:
            SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        # - name: Upload result to GitHub Code Scanning
        #   uses: github/codeql-action/upload-sarif@v2
        #   with:
        #     sarif_file: report
    push_to_registry:
      name: Push Docker image to Docker Hub
      runs-on: ubuntu-latest
      steps:
        - name: Check out the repo
          uses: actions/checkout@v3
        - name: Log in to Docker Hub
          uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}
        - name: Extract metadata (tags, labels) for Docker
          id: meta
          uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
          with:
            images: maupuert/api-demo
        - name: Build and push Docker image
          uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
          with:
            context: .
            push: true
            tags: ${{ steps.meta.outputs.tags }}
            labels: ${{ steps.meta.outputs.labels }}
    scan-dockerfile:
      runs-on: ubuntu-latest
      needs: sast
      steps:
        - name: Run Snyk to check Docker image for vulnerabilities
          uses: snyk/actions/docker@master
          continue-on-error: true
          env:
            SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
          with:
            image: maupuert/api-demo
    dast:
      name: Scan DAST with OWASP ZAP
      needs: [sca, scan-dockerfile]
      runs-on: ubuntu-latest
      steps:
        - name: checkout
          uses: actions/checkout@v3
          with:
            ref: main
        - name: ZAP Scan
          uses: zaproxy/action-api-scan@v0.1.1
          #uses: zaproxy/action-baseline@v0.6.1
          #uses: zaproxy/action-full-scan@v0.4.0
          with:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            docker_name: 'owasp/zap2docker-stable'
            format: openapi
            #target: 'http://testphp.vulnweb.com/'
            target: 'https://www.zaproxy.org/'
            rules_file_name: '.zap/rules.tsv'
            cmd_options: '-z "-config view.locale=es_ES"'




        





